# Generated by Django 5.0.6 on 2024-07-03 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='price',
            new_name='value',
        ),
        migrations.RemoveField(
            model_name='bank',
            name='total_money',
        ),
        migrations.AddField(
            model_name='bank',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=50000, max_digits=10),
        ),
        migrations.AddField(
            model_name='bank',
            name='interest_rate',
            field=models.FloatField(default=0.05),
        ),
        migrations.AddField(
            model_name='bank',
            name='mortgage_rate',
            field=models.FloatField(default=0.04),
        ),
        migrations.AddField(
            model_name='player',
            name='debt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='player',
            name='in_jail',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='position',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='hotel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='houses',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=1500, max_digits=10),
        ),
    ]
